name: Test Build
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Package files
        run: |
          echo "Packing files..."
          cat > release.txt << 'EOF'
          \*\*New Build Published\!\!\*\*
          >KernelVer: tester
          >DriverKSU: sukisu
          ```Features:
          [+] SUSFS à¶ž v1214
          [+] LZ4 v1.10.0 (Optimization armv8a)
          [+] TCP Pacing Tweaks
          [+] Wireguard Support
          [+] Magic Mount Support
          [+] BBR + ECN Support
          [+] TMPFS + RCU Support
          ```
          EOF
          
      - name: test
        uses: puernya/tg-bot-upload@main
        with:
          bot-id: ${{ secrets.BOT_ID }}
          chat-id: ${{ secrets.CHAT_ID }}
          topic-id: ${{ secrets.TOPIC_ID }}
          file-path: |
            *.txt
            ./*/*.yml
          caption-path: release.txt
